anthonykgrossfr_main_homepage:
    path:     /
    defaults: { _controller: AnthonykgrossfrMainBundle:Default:index }

anthonykgrossfr_contactez_moi:
    path:     /contact
    defaults: { _controller: AnthonykgrossfrMainBundle:Default:sendmail }
    
anthonykgrossfr_cv:
    path:     /cv
    defaults: { _controller: AnthonykgrossfrMainBundle:Default:cv }
    
anthonykgrossfr_blog:
    path:     /blog
    defaults: { _controller: AnthonykgrossfrMainBundle:Page:blog }
    
anthonykgrossfr_event:
    path:     /evenements
    defaults: { _controller: AnthonykgrossfrMainBundle:Page:event }

anthonykgrossfr_event2:
    path:     /event
    defaults: { _controller: AnthonykgrossfrMainBundle:Default:event }
    
anthonykgrossfr_project:
    path:     /projets
    defaults: { _controller: AnthonykgrossfrMainBundle:Page:project }

anthonykgrossfr_project2:
    path:     /project
    defaults: { _controller: AnthonykgrossfrMainBundle:Default:project }
    
anthonykgrossfr_page_lire:
    path:     /p/{name}
    defaults: { _controller: AnthonykgrossfrMainBundle:Page:lire }